### 리스트 보기
GET http://localhost:80/posts

### 특정 글 보기 (id = 2까지 두 개의 posts 임의로 만들어 놓음)
GET http://localhost:80/posts/1

### 존재 X 글
GET http://localhost:80/posts/3

### 검색 테스트
GET http://localhost:80/posts/search?title=첫

### 삭제하기 (존재하는 id)
DELETE http://localhost:80/posts/3

### 회원가입
POST http://localhost:80/users/join
Content-Type: application/json

{
  "userId": "test1",
  "pw": "1234"
}

### 회원가입 - 중복 아이디
POST http://localhost:80/users/join
Content-Type: application/json

{
  "userId": "testuser",
  "pw": "5678"
}

### 로그인
POST http://localhost:80/users/login
Content-Type: application/json

{
  "userId": "test1",
  "pw": "1234"
}

### 로그인 - 비밀번호 틀림
POST http://localhost:80/users/login
Content-Type: application/json

{
  "userId": "test1",
  "pw": "wrong"
}