### 1. 회원 등록
POST http://localhost/member/join
Content-Type: application/json

{

  "pw": "qwert!234",
  "name": "HeoJungMo",
  "phone": "4642-2532"
}

### 1. 회원 등록2
POST http://localhost/member/join
Content-Type: application/json

{
  "id": "admin",
  "pw": "qwert!234",
  "name": "일반유저",
  "phone": "1234-1234",
  "grade": "admin"
}

### 1. 회원 등록3
POST http://localhost/member/join
Content-Type: application/json

{
  "id": "person",
  "pw": "year@dream",
  "name": "신짱구",
  "phone": "7854-3321"
}

### 1. 회원 등록4
POST http://localhost/member/join
Content-Type: application/json

{
  "id": "manager",
  "pw": "manger@pass",
  "name": "김철수",
  "phone": "7854-3321"
}

### 1. 회원 등록5
POST http://localhost/member/join
Content-Type: application/json

{
  "id": "huneee",
  "pw": "babo!123",
  "name": "이훈이",
  "phone": "4612-1277"
}

### 2. 회원 목록
GET http://localhost/member/list

### 3. 회원 정보 상세보기
GET http://localhost/member/get/qqqwe

### 4. 회원 수정
PUT http://localhost/member/update/ppp97859
Content-Type: application/json

{
  "name": "update name",
  "phone": "1234-5678"
}

### 5. 회원 삭제
DELETE http://localhost/member/delete/ppp97859